_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "./output0803_grad_enhance_att_loss0305_iter1000/model_0014999.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 6
DATASETS:
  TRAIN: ("m3fd_trainval",)
  TEST:  ("m3fd_test",)
SOLVER:
  STEPS: (350000, 420000)
  MAX_ITER: 450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
